/**
 * Give the adjective for a country, for example "Malian" for "Mali".
 * The keys are the LC name headings that 370 $c uses, in lowercase.
 */

const DEMONYMS = {
  afghanistan: 'Afghan',
  albania: 'Albanian',
  algeria: 'Algerian',
  andorra: 'Andorran',
  angola: 'Angolan',
  'antigua and barbuda': 'Antiguan',
  argentina: 'Argentine',
  armenia: 'Armenian',
  'armenia (republic)': 'Armenian',
  australia: 'Australian',
  austria: 'Austrian',
  azerbaijan: 'Azerbaijani',
  bahamas: 'Bahamian',
  bahrain: 'Bahraini',
  bangladesh: 'Bangladeshi',
  barbados: 'Barbadian',
  belarus: 'Belarusian',
  belgium: 'Belgian',
  belize: 'Belizean',
  benin: 'Beninese',
  bhutan: 'Bhutanese',
  bolivia: 'Bolivian',
  'bosnia and herzegovina': 'Bosnian',
  'bosnia and hercegovina': 'Bosnian',
  botswana: 'Botswanan',
  brazil: 'Brazilian',
  brunei: 'Bruneian',
  bulgaria: 'Bulgarian',
  'burkina faso': 'Burkinabe',
  burma: 'Burmese',
  myanmar: 'Burmese',
  burundi: 'Burundian',
  'cabo verde': 'Cape Verdean',
  'cape verde': 'Cape Verdean',
  cambodia: 'Cambodian',
  cameroon: 'Cameroonian',
  canada: 'Canadian',
  'central african republic': 'Central African',
  chad: 'Chadian',
  chile: 'Chilean',
  china: 'Chinese',
  colombia: 'Colombian',
  comoros: 'Comorian',
  'congo (brazzaville)': 'Congolese',
  'congo (democratic republic)': 'Congolese',
  zaire: 'Zairean',
  'costa rica': 'Costa Rican',
  "côte d'ivoire": 'Ivorian',
  'ivory coast': 'Ivorian',
  croatia: 'Croatian',
  cuba: 'Cuban',
  cyprus: 'Cypriot',
  'czech republic': 'Czech',
  czechia: 'Czech',
  czechoslovakia: 'Czechoslovak',
  denmark: 'Danish',
  djibouti: 'Djiboutian',
  'dominican republic': 'Dominican',
  ecuador: 'Ecuadorian',
  egypt: 'Egyptian',
  'el salvador': 'Salvadoran',
  england: 'English',
  'equatorial guinea': 'Equatoguinean',
  eritrea: 'Eritrean',
  estonia: 'Estonian',
  eswatini: 'Swazi',
  swaziland: 'Swazi',
  ethiopia: 'Ethiopian',
  fiji: 'Fijian',
  finland: 'Finnish',
  france: 'French',
  gabon: 'Gabonese',
  gambia: 'Gambian',
  'georgia (republic)': 'Georgian',
  germany: 'German',
  'germany (east)': 'East German',
  'germany (west)': 'West German',
  ghana: 'Ghanaian',
  'great britain': 'British',
  greece: 'Greek',
  grenada: 'Grenadian',
  guatemala: 'Guatemalan',
  guinea: 'Guinean',
  'guinea-bissau': 'Bissau-Guinean',
  guyana: 'Guyanese',
  haiti: 'Haitian',
  honduras: 'Honduran',
  hungary: 'Hungarian',
  iceland: 'Icelandic',
  india: 'Indian',
  indonesia: 'Indonesian',
  iran: 'Iranian',
  iraq: 'Iraqi',
  ireland: 'Irish',
  israel: 'Israeli',
  italy: 'Italian',
  jamaica: 'Jamaican',
  japan: 'Japanese',
  jordan: 'Jordanian',
  kazakhstan: 'Kazakhstani',
  kenya: 'Kenyan',
  'korea (north)': 'North Korean',
  'korea (south)': 'South Korean',
  korea: 'Korean',
  kosovo: 'Kosovar',
  'kosovo (republic)': 'Kosovar',
  kuwait: 'Kuwaiti',
  kyrgyzstan: 'Kyrgyz',
  laos: 'Laotian',
  latvia: 'Latvian',
  lebanon: 'Lebanese',
  lesotho: 'Basotho',
  liberia: 'Liberian',
  libya: 'Libyan',
  liechtenstein: 'Liechtenstein',
  lithuania: 'Lithuanian',
  luxembourg: 'Luxembourgish',
  madagascar: 'Malagasy',
  malawi: 'Malawian',
  malaysia: 'Malaysian',
  maldives: 'Maldivian',
  mali: 'Malian',
  malta: 'Maltese',
  mauritania: 'Mauritanian',
  mauritius: 'Mauritian',
  mexico: 'Mexican',
  moldova: 'Moldovan',
  monaco: 'Monégasque',
  mongolia: 'Mongolian',
  montenegro: 'Montenegrin',
  morocco: 'Moroccan',
  mozambique: 'Mozambican',
  namibia: 'Namibian',
  nepal: 'Nepali',
  netherlands: 'Dutch',
  'new zealand': 'New Zealand',
  nicaragua: 'Nicaraguan',
  niger: 'Nigerien',
  nigeria: 'Nigerian',
  'north macedonia': 'Macedonian',
  'macedonia (republic)': 'Macedonian',
  'northern ireland': 'Northern Irish',
  norway: 'Norwegian',
  oman: 'Omani',
  pakistan: 'Pakistani',
  panama: 'Panamanian',
  'papua new guinea': 'Papua New Guinean',
  paraguay: 'Paraguayan',
  peru: 'Peruvian',
  philippines: 'Filipino',
  poland: 'Polish',
  portugal: 'Portuguese',
  'puerto rico': 'Puerto Rican',
  qatar: 'Qatari',
  romania: 'Romanian',
  russia: 'Russian',
  'russia (federation)': 'Russian',
  rwanda: 'Rwandan',
  'saint lucia': 'Saint Lucian',
  samoa: 'Samoan',
  'saudi arabia': 'Saudi',
  scotland: 'Scottish',
  senegal: 'Senegalese',
  serbia: 'Serbian',
  seychelles: 'Seychellois',
  'sierra leone': 'Sierra Leonean',
  singapore: 'Singaporean',
  slovakia: 'Slovak',
  slovenia: 'Slovenian',
  somalia: 'Somali',
  'south africa': 'South African',
  'south sudan': 'South Sudanese',
  'soviet union': 'Soviet',
  spain: 'Spanish',
  'sri lanka': 'Sri Lankan',
  sudan: 'Sudanese',
  suriname: 'Surinamese',
  sweden: 'Swedish',
  switzerland: 'Swiss',
  syria: 'Syrian',
  taiwan: 'Taiwanese',
  tajikistan: 'Tajikistani',
  tanzania: 'Tanzanian',
  thailand: 'Thai',
  togo: 'Togolese',
  tonga: 'Tongan',
  'trinidad and tobago': 'Trinidadian',
  tunisia: 'Tunisian',
  turkey: 'Turkish',
  turkmenistan: 'Turkmen',
  uganda: 'Ugandan',
  ukraine: 'Ukrainian',
  'united arab emirates': 'Emirati',
  'united states': 'American',
  uruguay: 'Uruguayan',
  uzbekistan: 'Uzbekistani',
  venezuela: 'Venezuelan',
  vietnam: 'Vietnamese',
  wales: 'Welsh',
  yemen: 'Yemeni',
  'yemen (republic)': 'Yemeni',
  yugoslavia: 'Yugoslav',
  zambia: 'Zambian',
  zimbabwe: 'Zimbabwean',
};

/**
 * Return the adjective for a country heading. Return undefined for a heading that is not in the table.
 * @param {string} country
 * @returns {string | undefined}
 */
export function demonymFor(country) {
  const key = String(country ?? '')
    .trim()
    .replace(/[.,;]+$/, '')
    .replace(/\s+/g, ' ')
    .toLowerCase();
  return Object.hasOwn(DEMONYMS, key) ? DEMONYMS[key] : undefined;
}
